In [1]:
n, m = map(int,input().split())

5 6


In [4]:
a = list(map(int,input().split()))

4 3 6 1 3


In [5]:
a

[4, 3, 6, 1, 3]

In [6]:
q = int(input())

3


In [7]:
q

3

In [8]:
se=[]

In [9]:
len(se)

0

In [10]:
while len(se)<q:
    se.append(list(map(int,input().split())))

1 3
1 5
2 3


In [11]:
a

[4, 3, 6, 1, 3]

In [12]:
se

[[1, 3], [1, 5], [2, 3]]

In [13]:
se[0][1]

3

In [14]:
kukan_mean = sum(a[se[0][0]-1:se[0][1]])/se[0][1]-se[0][0]+1

In [15]:
kukan_mean

4.333333333333333

In [16]:
import numpy as np

In [31]:
a_num = np.array(a)

In [32]:
a_num

array([4, 3, 6, 1, 3])

In [19]:
a[se[0][0]-1:se[0][1]]+2

TypeError: can only concatenate list (not "int") to list

In [20]:
if kukan_mean < m:
    a_num[se[0][0]-1:se[0][1]] += 2

In [21]:
a_num

array([6, 5, 8, 1, 3])

In [22]:
se

[[1, 3], [1, 5], [2, 3]]

In [23]:
len(se)

3

In [24]:
import math

In [49]:
a_num = np.array(a)

In [50]:
a_num

array([4, 3, 6, 1, 3])

In [51]:
for s in se:
    print(s)
    k_mean = np.mean(a_num[s[0]-1:s[1]])
#     k_mean = sum(a_num[s[0]-1:s[1]])/s[1]-s[0]+1
    print(k_mean)
    if k_mean < m:
        a_num[s[0]-1:s[1]] += math.ceil(m - k_mean)
        print(a_num)

[1, 3]
4.333333333333333
[6 5 8 1 3]
[1, 5]
4.6
[ 8  7 10  3  5]
[2, 3]
8.5


In [52]:
a_num

array([ 8,  7, 10,  3,  5])

In [69]:
a_list = a_num.tolist()

In [70]:
print(*a_list)

8 7 10 3 5


8
7
10
3
5
